### PR TITLE
Adding DisplayPort sample to the repository

### PR DESCRIPTION
**Pull request by mithro**

### CODE REVIEW

**Comment by hamsternz** [comment]
All good to go!

**Comment by hamsternz** [comment]
Now has h/w 8b/10b support

**Comment by mithro** [comment]
@hamsternz accidently put this message on the wrong thing, so here it is;

> Here's the change H/W 8b/10b makes in resource usage.
> 
> Single channel 800x600 colourbars
> 
> ```
>            H/W   S/W
> Registers  724   878
> LUTS       882  1397
> Occupied   295   552
> ```
> 
> Four channels 800x600 white
> 
> ```
>            H/W   S/W
> Registers  820   975  -16%
> LUTS       940  1473  -36%
> Occupied   320   562  -43%
> ```
> 
> It is all checked in now, and It should be all good for you to pull it.

**Comment by mithro** [comment]
Awesome!

**Pull request merged**
